# language: en
Feature: Defaults will be provided when customer doesn't specify search parameter
  As a customer
  If I don't specify search characteristics
  I would like to be provided with defaults

  Background:
    Given the repository:
      | title                            | description                                                                                                                                                                                                                                    | price    | reference | email                   | location.streetAddress         | location.city      | location.postalCode | location.countryCode |
      | Chef de projet marketing web h/f | Sous l’autorité du responsable marketing France, vous serez en charge de la définition d'actions marketing, de leur mise en œuvre, ainsi que de leur suivi. Votre objectif sera de développer le trafic et les ventes de nos sites partenaires | 70000.0  | REF-00001 | apply0@vente-privee.com | 249 Avenue du Président Wilson | La Plaine St Denis | 93210               | fr                   |
      | Chef de projet marketing web h/f | Sous l’autorité du responsable marketing France, vous serez en charge de la définition d'actions marketing, de leur mise en œuvre, ainsi que de leur suivi. Votre objectif sera de développer le trafic et les ventes de nos sites partenaires | 70000.0  | REF-00002 | apply1@vente-privee.com | 249 Avenue du Président Wilson | La Plaine St Denis | 93210               | fr                   |
      | Chef de projet marketing web h/f | Sous l’autorité du responsable marketing France, vous serez en charge de la définition d'actions marketing, de leur mise en œuvre, ainsi que de leur suivi. Votre objectif sera de développer le trafic et les ventes de nos sites partenaires | 70000.0  | REF-00003 | apply2@vente-privee.com | 249 Avenue du Président Wilson | La Plaine St Denis | 93210               | fr                   |
      | Chef de projet marketing web h/f | Sous l’autorité du responsable marketing France, vous serez en charge de la définition d'actions marketing, de leur mise en œuvre, ainsi que de leur suivi. Votre objectif sera de développer le trafic et les ventes de nos sites partenaires | 70000.0  | REF-00004 | apply3@vente-privee.com | 249 Avenue du Président Wilson | La Plaine St Denis | 93210               | fr                   |
      | Chef de projet marketing web h/f | Sous l’autorité du responsable marketing France, vous serez en charge de la définition d'actions marketing, de leur mise en œuvre, ainsi que de leur suivi. Votre objectif sera de développer le trafic et les ventes de nos sites partenaires | 70000.0  | REF-00005 | apply4@vente-privee.com | 249 Avenue du Président Wilson | La Plaine St Denis | 93210               | fr                   |
      | Chef de projet marketing web h/f | Sous l’autorité du responsable marketing France, vous serez en charge de la définition d'actions marketing, de leur mise en œuvre, ainsi que de leur suivi. Votre objectif sera de développer le trafic et les ventes de nos sites partenaires | 70000.0  | REF-00006 | apply5@vente-privee.com | 249 Avenue du Président Wilson | La Plaine St Denis | 93210               | fr                   |
      | Chef de projet marketing web h/f | Sous l’autorité du responsable marketing France, vous serez en charge de la définition d'actions marketing, de leur mise en œuvre, ainsi que de leur suivi. Votre objectif sera de développer le trafic et les ventes de nos sites partenaires | 70000.0  | REF-00007 | apply6@vente-privee.com | 249 Avenue du Président Wilson | La Plaine St Denis | 93210               | fr                   |
      | Chef de projet marketing web h/f | Sous l’autorité du responsable marketing France, vous serez en charge de la définition d'actions marketing, de leur mise en œuvre, ainsi que de leur suivi. Votre objectif sera de développer le trafic et les ventes de nos sites partenaires | 70000.0  | REF-00008 | apply7@vente-privee.com | 249 Avenue du Président Wilson | La Plaine St Denis | 93210               | fr                   |
      | Chef de projet marketing web h/f | Sous l’autorité du responsable marketing France, vous serez en charge de la définition d'actions marketing, de leur mise en œuvre, ainsi que de leur suivi. Votre objectif sera de développer le trafic et les ventes de nos sites partenaires | 70000.0  | REF-00009 | apply8@vente-privee.com | 249 Avenue du Président Wilson | La Plaine St Denis | 93210               | fr                   |
      | Chef de projet marketing web h/f | Sous l’autorité du responsable marketing France, vous serez en charge de la définition d'actions marketing, de leur mise en œuvre, ainsi que de leur suivi. Votre objectif sera de développer le trafic et les ventes de nos sites partenaires | 70000.0  | REF-00010 | apply9@vente-privee.com | 249 Avenue du Président Wilson | La Plaine St Denis | 93210               | fr                   |
      | Vente Appartement 4 pièces       | Comme neuf !! Ce grand 4 pièces, situé dans une rue calme, proche de la défense, vient d'être refait a neuf. Cuisine équipée, terrasse, WC séparés                                                                                             | 394000.0 | REF-00011 | foo10@bar.com           | 5 rue Marcel Sembat            | Courbevoie         | 92400               | fr                   |
      | Vente Appartement 4 pièces       | Comme neuf !! Ce grand 4 pièces, situé dans une rue calme, proche de la défense, vient d'être refait a neuf. Cuisine équipée, terrasse, WC séparés                                                                                             | 394000.0 | REF-00012 | foo11@bar.com           | 5 rue Marcel Sembat            | Courbevoie         | 92400               | fr                   |
      | Vente Appartement 4 pièces       | Comme neuf !! Ce grand 4 pièces, situé dans une rue calme, proche de la défense, vient d'être refait a neuf. Cuisine équipée, terrasse, WC séparés                                                                                             | 394000.0 | REF-00013 | foo12@bar.com           | 5 rue Marcel Sembat            | Courbevoie         | 92400               | fr                   |
      | Vente Appartement 4 pièces       | Comme neuf !! Ce grand 4 pièces, situé dans une rue calme, proche de la défense, vient d'être refait a neuf. Cuisine équipée, terrasse, WC séparés                                                                                             | 394000.0 | REF-00014 | foo13@bar.com           | 5 rue Marcel Sembat            | Courbevoie         | 92400               | fr                   |
      | Vente Appartement 4 pièces       | Comme neuf !! Ce grand 4 pièces, situé dans une rue calme, proche de la défense, vient d'être refait a neuf. Cuisine équipée, terrasse, WC séparés                                                                                             | 394000.0 | REF-00015 | foo14@bar.com           | 5 rue Marcel Sembat            | Courbevoie         | 92400               | fr                   |
      | Vente Appartement 4 pièces       | Comme neuf !! Ce grand 4 pièces, situé dans une rue calme, proche de la défense, vient d'être refait a neuf. Cuisine équipée, terrasse, WC séparés                                                                                             | 394000.0 | REF-00016 | foo15@bar.com           | 5 rue Marcel Sembat            | Courbevoie         | 92400               | fr                   |
      | Vente Appartement 4 pièces       | Comme neuf !! Ce grand 4 pièces, situé dans une rue calme, proche de la défense, vient d'être refait a neuf. Cuisine équipée, terrasse, WC séparés                                                                                             | 394000.0 | REF-00017 | foo16@bar.com           | 5 rue Marcel Sembat            | Courbevoie         | 92400               | fr                   |
      | Vente Appartement 4 pièces       | Comme neuf !! Ce grand 4 pièces, situé dans une rue calme, proche de la défense, vient d'être refait a neuf. Cuisine équipée, terrasse, WC séparés                                                                                             | 394000.0 | REF-00018 | foo17@bar.com           | 5 rue Marcel Sembat            | Courbevoie         | 92400               | fr                   |
      | Vente Appartement 4 pièces       | Comme neuf !! Ce grand 4 pièces, situé dans une rue calme, proche de la défense, vient d'être refait a neuf. Cuisine équipée, terrasse, WC séparés                                                                                             | 394000.0 | REF-00019 | foo18@bar.com           | 5 rue Marcel Sembat            | Courbevoie         | 92400               | fr                   |

  @done
  @#14
  Scenario: Defaults are used when no search characteristics are provided
    Given I am a customer
    When I search all classifieds
    Then I get "19" items
    And the items are:
      | title                      | price    | reference | email         | location.streetAddress | location.city | location.postalCode | location.countryCode |
      | Vente Appartement 4 pièces | 394000.0 | REF-00019 | foo18@bar.com | 5 rue Marcel Sembat    | Courbevoie    | 92400               | fr                   |
      | Vente Appartement 4 pièces | 394000.0 | REF-00018 | foo17@bar.com | 5 rue Marcel Sembat    | Courbevoie    | 92400               | fr                   |
    And "self" link "pageIndex" should be "0"
    And "self" link "itemsPerPage" should be "2"
    And "self" link "sort" should be "created:desc"
